from course_mcp.mcp_schemas.calendar import GET_UPCOMING_WORK_OUTPUT_SCHEMA
from course_mcp.mcp_schemas.search import (
    SEARCH_COURSE_FILE_OUTPUT_SCHEMA,
    SEARCH_COURSE_OUTPUT_SCHEMA,
)
from course_mcp.mcp_schemas.piazza import (
    GET_PIAZZA_POST_OUTPUT_SCHEMA,
    LIST_PIAZZA_COURSES_OUTPUT_SCHEMA,
    LIST_PIAZZA_POSTS_OUTPUT_SCHEMA,
    SEARCH_PIAZZA_POSTS_OUTPUT_SCHEMA,
)

__all__ = [
    "GET_UPCOMING_WORK_OUTPUT_SCHEMA",
    "SEARCH_COURSE_FILE_OUTPUT_SCHEMA",
    "SEARCH_COURSE_OUTPUT_SCHEMA",
    "GET_PIAZZA_POST_OUTPUT_SCHEMA",
    "LIST_PIAZZA_COURSES_OUTPUT_SCHEMA",
    "LIST_PIAZZA_POSTS_OUTPUT_SCHEMA",
    "SEARCH_PIAZZA_POSTS_OUTPUT_SCHEMA",
]
